#pragma once
#ifndef UI_H_
#define UI_H_

//FRAME
#define LEVEL_UI_SIZEX 600.0f
#define LEVEL_UI_SIZEY 700.0f
#define SHOP_UI_SIZEX 1600.0f
#define SHOP_UI_SIZEY 900.0f
#define BATTLEMENU_UI_SIZEX 500.0f
#define BATTLEMENU_UI_SIZEY 600.0f

//X
#define XBTN_SIZE 64.0f
#define LEVELXBTN_POSX  (LEVEL_UI_SIZEX / 2)
#define LEVELXBTN_POSY  (-LEVEL_UI_SIZEY / 2)
#define SHOPXBTN_POSX (SHOP_UI_SIZEX / 2)
#define SHOPXBTN_POSY (-SHOP_UI_SIZEY / 2)

//LEVEL
#define LEVELSTARTBTN_SIZEX 320.0f
#define LEVELSTARTBTN_SIZEY 70.0f
#define LEVELSTARTBTN_POSY (LEVEL_UI_SIZEY / 2)

//SHOP&UPGRADE
#define SHOPBULLET_SIZE 400.0f
#define SHOPBULLET_02_POSX -300.0f
#define SHOPBULLET_03_POSX 300.0f
#define SHOPBULLET_POSY 0.0f
#define SHOPBUYBTN_SIZEX 200.0f
#define SHOPBUYBTN_SIZEY 50.0f
#define SHOPBUYBTN_02_POSX (SHOPBULLET_02_POSX)
#define SHOPBUYBTN_03_POSX (SHOPBULLET_03_POSX)
#define SHOPBUYBTN_POSY (SHOPBUYBTN_SIZEY + SHOPBULLET_POSY + SHOPBULLET_SIZE / 2)

#define UPGRADEBG_SIZEX 900.0f
#define UPGRADEBG_SIZEY 200.0f
#define UPGRADEBG_POSX -100.0f
#define UPGRADEBG_SHOOTSPEED_POSY -225.0f
#define UPGRADEBG_HP_POSY (UPGRADEBG_SHOOTSPEED_POSY + 225.0f)
#define UPGRADEBG_SHIELD_POSY (UPGRADEBG_HP_POSY + 225.0f)
#define UPGRADE_LEVEL_SIZEX 150.0f
#define UPGRADE_LEVEL_SIZEY 100.0f
#define UPGRADE_BTN_SIZEX 250.0f
#define UPGRADE_BTN_SIZEY 60.0f
#define UPGRADE_BTN_POSX (UPGRADEBG_POSX + UPGRADEBG_SIZEX / 2 + SHOPBUYBTN_SIZEX - 50.0f)

//BATTLEMENU
#define BATTLEMENUCONTINUEBTN_POSY (-BATTLEMENU_UI_SIZEY / 5)
#define BATTLEMENUQUITBTN_POSY  (BATTLEMENU_UI_SIZEY / 5)
#define BATTLEMENUBTN_SIZEX 320.0f
#define BATTLEMENUBTN_SIZEY 70.0f

typedef enum
{
	LEVELCHOOSEUI = 0,
	SHOPMAINUI,
	SHOPUI,
	UPGRADEUI,
	BATTLEMENUUI,
	RESULTUI,
	NOTHINGUI
}UI;

void InitUI();
void UninitUI();
void UpdateUI();
void DrawUI();

void ShowUI(UI ui);

#endif // !UI_H_